// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCc9GAUPXEF_Cz1wK-MGfNQlizTB5HE9E',
    appId: '1:850502517034:web:2895f3ffa7976994cd5e53',
    messagingSenderId: '850502517034',
    projectId: 'taskmanager-ebea8',
    authDomain: 'taskmanager-ebea8.firebaseapp.com',
    storageBucket: 'taskmanager-ebea8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgMoqad9i12Q7-z0bVNc1yetVqwt7oySs',
    appId: '1:850502517034:android:ff4f6c0459cbccd3cd5e53',
    messagingSenderId: '850502517034',
    projectId: 'taskmanager-ebea8',
    storageBucket: 'taskmanager-ebea8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRa3LYNfRU_ehpruIWIeWMArm6rqh-EUQ',
    appId: '1:850502517034:ios:3d2f1ffd7c0cba1ccd5e53',
    messagingSenderId: '850502517034',
    projectId: 'taskmanager-ebea8',
    storageBucket: 'taskmanager-ebea8.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRa3LYNfRU_ehpruIWIeWMArm6rqh-EUQ',
    appId: '1:850502517034:ios:73ca2e2152c840e3cd5e53',
    messagingSenderId: '850502517034',
    projectId: 'taskmanager-ebea8',
    storageBucket: 'taskmanager-ebea8.appspot.com',
    iosBundleId: 'com.example.taskmanager.RunnerTests',
  );
}
